// <auto-generated />
using System;
using ContractorsDesk.DataStore.Account;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractorsDesk.DataStore.Account.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20241119143354_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Super Admin",
                            NormalizedName = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Customer Support",
                            NormalizedName = "Customer Support"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Super IT",
                            NormalizedName = "Super IT"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Company Owner",
                            NormalizedName = "Company Owner"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Project Manager",
                            NormalizedName = "Project Manager"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Assistant Project Manager",
                            NormalizedName = "Assistant Project Manager"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Bookkeeper",
                            NormalizedName = "Bookkeeper"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Company IT",
                            NormalizedName = "Company IT"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Office Manager",
                            NormalizedName = "Office Manager"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Client",
                            NormalizedName = "Client"
                        });
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 3,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 5,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 7,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 8,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 9,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 10,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 26,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 27,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 28,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 1,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 3,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 9,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 10,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 26,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 27,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 28,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 2,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 4,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 6,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 9,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 10,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 14,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 15,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 11,
                            RoleId = 8
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 12,
                            RoleId = 8
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 1,
                            RoleId = 9
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 3,
                            RoleId = 9
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 5,
                            RoleId = 9
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 7,
                            RoleId = 9
                        },
                        new
                        {
                            Id = 32,
                            PermissionId = 9,
                            RoleId = 9
                        },
                        new
                        {
                            Id = 33,
                            PermissionId = 26,
                            RoleId = 9
                        },
                        new
                        {
                            Id = 34,
                            PermissionId = 27,
                            RoleId = 9
                        },
                        new
                        {
                            Id = 35,
                            PermissionId = 28,
                            RoleId = 9
                        },
                        new
                        {
                            Id = 36,
                            PermissionId = 29,
                            RoleId = 10
                        });
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireLogOn")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "CH Anderson Construction"
                        });
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage All Jobs",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Own Jobs",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage All Estimates",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Own Estimates",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage All Action Items",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Own Action Items",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Company Users",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Company Roles",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Schedules",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Finance",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Client Websites",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Company Email",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Company SEO",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Client Onboarding",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Access to Third-party Services",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage System Users",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage System Roles",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Account Owners",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage System Permissions",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Client Websites",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Client Onboarding",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Access to Third-party Services",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Company Email",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Company SEO",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage Clients",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Can Assign Jobs",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Can Assign Estimates",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Can Assign Action Items",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            DateCreated = new DateTime(2024, 10, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Can Access Client Jobs",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.PermissionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PermissionCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "System Permissions"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Company Permissions"
                        });
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.RoleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "System"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Company"
                        });
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.UserBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserBookmarks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationRole", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.RoleCategory", "Category")
                        .WithMany("Roles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationRoleClaim", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.Permission", "Permission")
                        .WithMany("RoleClaims")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractorsDesk.Core.Models.ApplicationRole", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationUser", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractorsDesk.Core.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.Permission", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.PermissionCategory", "Category")
                        .WithMany("Permissions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.UserBookmark", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.ApplicationUser", "User")
                        .WithMany("UserBookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ContractorsDesk.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationRole", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserBookmarks");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.Permission", b =>
                {
                    b.Navigation("RoleClaims");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.PermissionCategory", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ContractorsDesk.Core.Models.RoleCategory", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
