CREATE TABLE [dbo].[QBCustomers] (
    [ID]                  UNIQUEIDENTIFIER NOT NULL,
    [ListID]              NVARCHAR (MAX)   NOT NULL,
    [Name]                NVARCHAR (MAX)   NULL,
    [LastName]            NVARCHAR (MAX)   NULL,
    [FullName]            NVARCHAR (MAX)   NULL,
    [CompanyName]         NVARCHAR (MAX)   NULL,
    [Address]             NVARCHAR (MAX)   NULL,
    [NACE]                NVARCHAR (MAX)   NULL,
    [Balance]             DECIMAL (18, 2)  NULL,
    [Currency]            NVARCHAR (MAX)   NULL,
    [Phone]               NVARCHAR (MAX)   NULL,
    [Email]               NVARCHAR (MAX)   NULL,
    [SecondaryEmail]      NVARCHAR (MAX)   NULL,
    [IsActive]            BIT              NULL,
    [Level]               INT              NULL,
    [ParentID]            NVARCHAR (MAX)   NULL,
    [JobStatus]           NVARCHAR (MAX)   NULL,
    [JobStartDate]        DATETIME2 (7)    NULL,
    [JobProjectedEndDate] DATETIME2 (7)    NULL,
    [JobEndDate]          DATETIME2 (7)    NULL,
    [JobDesc]             NVARCHAR (MAX)   NULL,
    [VATNumber]           NVARCHAR (MAX)   NULL,
    [NUINumber]           NVARCHAR (MAX)   NULL,
    [TimeCreated]         DATETIME2 (7)    NULL,
    [TimeModified]        DATETIME2 (7)    NULL,
    [CreatedBy]           NVARCHAR (MAX)   NULL,
    [UpdatedBy]           NVARCHAR (MAX)   NULL,
    [City] NVARCHAR(MAX) NULL, 
    [State] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_QBCustomers] PRIMARY KEY CLUSTERED ([ID] ASC)
);

